config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/FAIR_eva:
      branch: main
      repo: https://github.com/EOSC-synergy/FAIR_eva
    github.com/EOSC-synergy/sqa-composer-templates:
      branch: feature/dynamic_tool_gathering
      repo: https://github.com/EOSC-synergy/sqa-composer-templates
environment: {}
sqa_criteria:
  QC.FAIR:
    repos:
      this_repo:
        commands:
        - curl localhost
        container: qc.fair_cloudy-celadon-hare
timeout: 600
