services:
  qc.fair_cloudy-celadon-hare:
    command: sleep 6000000
    image: ferag/fair_eva
    volumes:
    - source: ./
      target: /sqaaas-build
      type: bind
    working_dir: /sqaaas-build
version: '3.7'
